# Generated by Django 3.1.2 on 2020-10-26 01:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Day')),
                ('main_image', models.ImageField(upload_to='main_ars_images/', verbose_name='Main image')),
                ('quote', models.TextField(default='', verbose_name='Favorite quote')),
                ('text', models.TextField(default='', verbose_name='What happened today?')),
                ('published', models.DateTimeField(default=datetime.datetime(2020, 10, 26, 4, 34, 6, 396227), verbose_name='Date')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='article_images/', verbose_name='Image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='days.post', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Image for a day',
                'verbose_name_plural': 'Images for a days',
            },
        ),
    ]
