# Generated by Django 3.1.2 on 2020-10-26 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 4, 51, 28, 577749), verbose_name='Date'),
        ),
    ]
